// TestingApp/projects/components/src/lib/menu/menu.component.ts
import { Component, Input, OnInit } from '@angular/core';

@Component({
  selector: 'lib-menu',
  template: `
    <nav aria-label="Menu">
      <ul>
        <ng-container *ngFor="let menuItem of menuItems">
          <lib-menu-item
            *ngIf="isString(menuItem)"
            [title]="toString(menuItem)"
            [href]="toString(menuItem)"
          >
          </lib-menu-item>
          <lib-menu-item
            *ngIf="!isString(menuItem)"
            [title]="menuItem[0]"
            [href]="menuItem[0]"
          >
            <lib-sub-menu
              submenu
              [subMenuItems]="toArray(menuItem)"
            ></lib-sub-menu
          ></lib-menu-item>
        </ng-container>
      </ul>
    </nav>
  `,
  styleUrls: ['./menu.component.css'],
})
export class MenuComponent implements OnInit {
  @Input() menuItems!: Array<string | Array<string>>;

  ngOnInit() {
    console.log(this.menuItems);
  }
  isString(menuItem: string | Array<string>): boolean {
    return typeof menuItem === 'string';
  }
  toArray(menuItem: string | Array<string>): Array<string> {
    return menuItem as Array<string>;
  }
  toString(menuItem: string | Array<string>): string {
    return menuItem as string;
  }
}

// WebComponents/menu/menu.js
export default class Menu extends HTMLElement {
    constructor() {
        super();

        let menuItems;
        // Creates a shadow root
        this.root = this.attachShadow({ mode: 'closed' });

        // Render HTML
        this.root.innerHTML = `
        <nav aria-label="Menu">
            <ul>
            
            </ul>
        </nav>
      `;
    }
    connectedCallback() {
        this.menuItems.forEach((item) => {
            // console.log(item);
            if (typeof item === 'string') {
                const menuItem = document.createElement('my-menu-item');
                menuItem.setAttribute('title', item);
                menuItem.setAttribute('href', item);
                this.root.querySelector('ul').appendChild(menuItem);
            } else {
                const menuItem = document.createElement('my-menu-item');
                menuItem.setAttribute('title', item[0]);
                menuItem.setAttribute('href', item[0]);
                menuItem.setAttribute('hasSubmenu', true);

                const subMenu = document.createElement('my-sub-menu');
                subMenu.subMenuItems = item;
                menuItem.appendChild(subMenu);
                this.root.querySelector('ul').appendChild(menuItem);
            }
        });
        // console.log(this.root.querySelector('ul'));
    }
}
